schema_version = "1.0.0"
id = "Multires_Projecting_Toolset"
version = "0.9.0"
name = "Multires Projecting Toolset"
tagline = "texture projection tool with support for multiple cameras"
maintainer = "Packsod"
type = "add-on"
# website = "https://extensions.blender.org/add-ons/my-example-package/"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
# platforms = ["windows-x64"]
